Pseudo versions and branches support
sirkon/goproxy pull request #5
Opened 2019-05-18 13:26 UTC by sirkon

Logic behind: 
* `<module path>/@v/<revision>.stat` now checks if `<revision>` is correct semver value
    * if it is it checks if this is pseudo version `v.X.Y.Z-[pre-]yyyymmddhhmmss-<sha>`.
        * if it is it tries to build pseudo version from commits and tags bound to them
        * just go further with given semver tag otherwise
    * if it is not it supposes the `<revision>` is branch or tag name and tries to build pseudo version from
commits of this branch and tags bound to them
* `<module path>/@v/<revision>.[mod|zip]` determine if `<version>` is a pseudo version
    * If it is the plugin tries to take go.mod/archive with given SHA. Switch to regular path if failed getting info with the SHA
    * just takes an info with given semver value

2019-05-20 12:45 UTC, vitalyisaev2 requested changes

2019-05-20 12:45 UTC, vitalyisaev2 commented on plugin_gitlab/module.go
> +		moment[:4], moment[5:7], moment[8:10], moment[11:13], moment[14:16], moment[17:19],
я бы предложил дать говорящие названия этим переменным, как бе самодокументирующийся код)

2019-05-20 13:00 UTC, alyoshka approved these changes

2019-05-20 13:22 UTC, sirkon commented on plugin_gitlab/module.go
> +		moment[:4], moment[5:7], moment[8:10], moment[11:13], moment[14:16], moment[17:19],
@vitalyisaev2 я хз какие здесь "говорящие" названия дать. `datetime` длинновато получается, `moment`, нмв, вполне подходит под это определение

2019-05-20 14:24 UTC, vitalyisaev2 commented on plugin_gitlab/module.go
> +		moment[:4], moment[5:7], moment[8:10], moment[11:13], moment[14:16], moment[17:19],
я имею в виду, что `var x = moment[:4]`, `var ololo = moment[5:7]` и так далее, чтобы было понятн без погружения в контекст, из чего состоит эта псевдоверсия

2019-05-20 17:35 UTC, sirkon commented on plugin_gitlab/module.go
> +		moment[:4], moment[5:7], moment[8:10], moment[11:13], moment[14:16], moment[17:19],
поправил

2019-05-21 10:37 UTC, zeslava approved these changes

2019-05-21 11:26 UTC, vitalyisaev2 approved these changes

2019-05-21 12:14 UTC, merged